version: '3.8'

services:
  ebay-alert:
    build: .
    container_name: ebay_alert_bot
    environment:
      - TOKEN=${TOKEN}
      - CHAT_ID=${CHAT_ID}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
    volumes:
      - ./data:/app/data
    entrypoint: ["/bin/bash", "-c", "echo '$CRON_SCHEDULE /app/run_get_posts.sh >> /var/log/cron.log 2>&1' > /etc/cron.d/ebay_alert && chmod 0644 /etc/cron.d/ebay_alert && crontab /etc/cron.d/ebay_alert && cron && python main.py"]
    restart: always
